const data = {
  products: [
    {
      _id: 1,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?a=2",
      price: 200,
      brand: "Nikeike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 2,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?b=2",
      price: 200,
      brand: "",
      rating: 1,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 3,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?c=2",
      price: 200,
      brand: "",
      rating: 0.5,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 4,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?d=2",
      price: 200,
      brand: "",
      rating: 0.1,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 4,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?d=2",
      price: 200,
      brand: "",
      rating: 0.1,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 4,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?d=2",
      price: 200,
      brand: "",
      rating: 0.1,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 4,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?d=2",
      price: 200,
      brand: "",
      rating: 0.1,
      numReviews: 10,
      description: "high quality ",
    },
    {
      _id: 4,
      name: "Nike",
      category: "shirts",
      image: "https://picsum.photos/200/300?d=2",
      price: 200,
      brand: "",
      rating: 0.1,
      numReviews: 10,
      description: "high quality ",
    },
  ],
};

export default data;
